spring:
  data:
    mongodb:
      uri: mongodb://${{MONGO_INITDB_ROOT_USERNAME}}:${{MONGO_INITDB_ROOT_PASSWORD}}@${{RAILWAY_PRIVATE_DOMAIN}}:27017  # Railway will provide this
      auto-index-creation: false

jwt:
  token:
    validity: 18000000
    secret:  bSpklEFrxjndNKXEHx+dINawVmCwGyjJyws1zhqlkJc=
