spring:
  data:
    mongodb:
      uri: mongodb://mongo:OhHtyGoHkgiHjtOvwcuaSEJGeUmJYXEs@mongodb.railway.internal:27017/blog  # Railway will provide this
      auto-index-creation: false

jwt:
  token:
    validity: 18000000
    secret:  bSpklEFrxjndNKXEHx+dINawVmCwGyjJyws1zhqlkJc=
