spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    mongodb:
      uri: mongodb://mongo:OhHtyGoHkgiHjtOvwcuaSEJGeUmJYXEs@autorack.proxy.rlwy.net:37168/blog?ssl=true
      auto-index-creation: false

jwt:
  token:
    validity: 18000000
    secret:  bSpklEFrxjndNKXEHx+dINawVmCwGyjJyws1zhqlkJc=
