spring:
  data:
    mongodb:
      uri: mongodb://${{MONGO_INITDB_ROOT_USERNAME}}:XiPLYyQtqIAdZyBdCqxviUWGptIjgjcC@${{RAILWAY_PRIVATE_DOMAIN}}:27017/blog  # Railway will provide this
      auto-index-creation: false

jwt:
  token:
    validity: 18000000
    secret:  bSpklEFrxjndNKXEHx+dINawVmCwGyjJyws1zhqlkJc=
