spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    mongodb:
      uri: ${MONGO_URL}/blog
      database: blog
      authentication-database: admin
      auto-index-creation: false

jwt:
  token:
    validity: 18000000
    secret:  bSpklEFrxjndNKXEHx+dINawVmCwGyjJyws1zhqlkJc=
